apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-secret
  # Replace with the namespace where you want the secret to be created
  namespace: {{ .Release.Namespace }} #observability
spec:
  refreshInterval: "1h" # Syncs the secret every hour
  secretStoreRef:
    name: vault-backend-cluster
    kind: ClusterSecretStore
  target:
    name: grafana-secret # The name of the Kubernetes secret to be created
    creationPolicy: Owner
  data:
    - secretKey: admin-user #secret mein yeh name se key banayega
      remoteRef:
        key: grafana # Path inside the KV engine
        property: admin-user #teh databse path mein se kaunse key ko fetch karna
    - secretKey: admin-password
      remoteRef:
        key: grafana
        property: admin-password