admin:
  existingSecret: "grafana-secret"
nodeSelector:
  type: dependent_services

service:
  type: NodePort
  port: 80

persistence:
  enabled: true
  storageClassName: csi-hostpath-sc
  accessModes:
    - ReadWriteOnce
  size: 5Gi
  type: pvc

sidecar:
  dashboards:
    enabled: true
    label: grafana_dashboard
    labelValue: "dynamic"
    provider:
      name: sidecarProvider
      orgid: 1
      folder: 'Grafana Dashboards'
      type: file
      # allow updating provisioned dashboards from the UI
      allowUiUpdates: false

  datasources:
    enabled: true
    label: grafana_datasource
    labelValue: "dynamic"
