apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-apiurl-secret
  # Replace with the namespace where you want the secret to be created
  namespace: {{ .Release.Namespace }} #observability
spec:
  refreshInterval: "1h" # Syncs the secret every hour
  secretStoreRef:
    name: vault-backend-cluster
    kind: ClusterSecretStore
  target:
    name: alertmanager-slack-secret # The name of the Kubernetes secret to be created
    creationPolicy: Owner
  data:
    - secretKey: slack-api-url #secret mein yeh name se key banayega
      remoteRef:
        key: alertmanager # Path inside the KV engine
        property: slack-api-url #teh databse path mein se kaunse key ko fetch karna