name: CI-CD Pipeline

permissions:
  contents: write
on:
  push:
    # branches: [ main ]
    tags:
      - "v*.*.*"

  workflow_dispatch:
    inputs:
      tag_version:
        description: "Docker image tag (e.g., 1.0.0) Note: not for GIT tags[test purpose]"
        required: true
        type: string
    

jobs:
  build-test-push:
    name: CI
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
           python-version: "3.11" 

      - name: Installing dependencies
        run: make build

      - name: Run tests
        run: make test

      - name: Lint code (flake8)
        run: make lint

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Determine Docker Image Version
        id: vars
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            VERSION="${{ github.event.inputs.tag_version }}"
          else
            VERSION="${GITHUB_REF#refs/tags/v}"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Build & Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_REPO }}:${{ steps.vars.outputs.VERSION }} .
          docker push ${{ secrets.DOCKER_REPO }}:${{ steps.vars.outputs.VERSION }}

  update-helm-values:
    name: CD
    needs: build-test-push
    runs-on: self-hosted

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set remote URL
        run: |
          git remote set-url origin https://github.com/${{ github.repository }}.git

      - name: Determine Docker Image Version
        id: vars
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            VERSION="${{ github.event.inputs.tag_version }}"
          else
            VERSION="${GITHUB_REF#refs/tags/v}"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Update image tag in values.yaml
        run: |
          sed -i "s/tag: .*/tag: \"${{ steps.vars.outputs.VERSION }}\"/" helm-charts/application/backend/values.yaml

      - name: Commit & Push Changes
        run: |
          git config --global user.email "${{ secrets.EMAIL }}"
          git config --global user.name "ahmedbilal-7191"

          git add helm-charts/application/backend/values.yaml
          git commit -m "Update image tag to ${{ steps.vars.outputs.VERSION }}"
          git push origin main
